services:
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - postgres
#      - keycloak
    networks:
      - bcb_network

  postgres:
    image: postgres:15
    container_name: bigchatbrasil_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bigchatbrasil
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bcb_network

#  keycloak:
#    container_name: auth_keycloak
#    image: quay.io/keycloak/keycloak:20.0.3
#    environment:
#      - KEYCLOAK_USER=admin
#      - KEYCLOAK_PASSWORD=admin
#    ports:
#      - "8443:8443"
#    command:
#      - "start-dev"
#      - "--http-port=8443"
#    volumes:
#      - ../.docker/keycloak:/opt/keycloak/data/h2:rw
#    networks:
#      - bcb_network
#    extra_hosts:
#      - "keycloak.internal:127.0.0.1"

volumes:
  postgres_data:

networks:
  bcb_network:
    driver: bridge